name: Node.js CI on Pull request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    draft: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # You can specify any Node.js version you prefer

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test